CREATE TABLE IF NOT EXISTS TSO_TIMESTAMP (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    TSO_PATH VARCHAR(255) NOT NULL COMMENT 'TSO 的标识',
    TSO_TS NUMERIC(20, 0) NOT NULL COMMENT 'TSO 时间戳，全局唯一且自增，无符号 64 位数字',
    TSO_NODE VARCHAR(255) NOT NULL COMMENT '最近更新的节点信息',
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
    PRIMARY KEY (ID),
    UNIQUE INDEX UNIQUE_IDENTIFIER (TSO_PATH) COMMENT '保证标识符的唯一性'
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='存储 TSO 时间戳信息';

CREATE TABLE IF NOT EXISTS ETCD_SHIM_KV (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    ETCD_KEY VARCHAR(255) NOT NULL COMMENT 'KV 的 KEY',
    ETCD_VALUE VARCHAR(255) NOT NULL COMMENT 'KV 的 VALUE',
    ETCD_OLD_VALUE VARCHAR(255) NOT NULL COMMENT 'KV 的 VALUE(前值)',
    ETCD_CREATE_REVISION INTEGER,
    ETCD_PREV_REVISION INTEGER,
    ETCD_LEASE_ID INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    DELETED TIMESTAMP COMMENT '删除时间',
    PRIMARY KEY (ID),
    INDEX NAME_INDEX (ETCD_KEY),
    INDEX NAME_ID_INDEX (ETCD_KEY, ID),
    INDEX ID_DELETED_INDEX (ID, ETCD_DELETED),
    INDEX PREV_REVISION_INDEX (ETCD_PREV_REVISION),
    UNIQUE INDEX NAME_PREV_REVISION_UINDEX (ETCD_KEY, ETCD_PREV_REVISION)
);

CREATE TABLE IF NOT EXISTS ETCD_SHIM_LEASE (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    ETCD_LEASE_ID INTEGER NOT NULL COMMENT '租期 的 ID',
    ETCD_TTL INTEGER NOT NULL COMMENT '租期 的 时间长度，单位：秒',
    ETCD_CREATED INTEGER,
    ETCD_DELETED INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
    PRIMARY KEY (ID)
);