CREATE TABLE TSO_TIMESTAMP (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    TSO_PATH VARCHAR(255) NOT NULL COMMENT 'TSO 的标识',
    TSO_TS NUMERIC(20, 0) NOT NULL COMMENT 'TSO 时间戳，全局唯一且自增，无符号 64 位数字',
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
    UPDATE_NODE VARCHAR(100) NOT NULL COMMENT '最近更新的节点信息',
    PRIMARY KEY (ID),
    UNIQUE INDEX UNIQUE_IDENTIFIER (TSO_PATH) COMMENT '保证标识符的唯一性'
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='存储 TSO 时间戳信息';