CREATE TABLE IF NOT EXISTS TSO_TIMESTAMP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主键
    TSO_PATH TEXT NOT NULL, -- TSO 的标识
    TSO_TS TEXT NOT NULL, -- TSO 时间戳，全局唯一且自增，无符号 64 位数字
    TSO_NODE TEXT NOT NULL, -- 最近更新的节点信息
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 新增时间
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 最近更新时间
    UNIQUE (TSO_PATH)
);

CREATE TABLE IF NOT EXISTS ETCD_SHIM_KV (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主键
    ETCD_KEY TEXT NOT NULL -- KV 的 KEY
    ETCD_VALUE TEXT NOT NULL -- KV 的 VALUE
    ETCD_OLD_VALUE TEXT NOT NULL -- KV 的 VALUE(前值)
    ETCD_CREATE_REVISION INTEGER,
    ETCD_PREV_REVISION INTEGER,
    ETCD_LEASE_ID INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 新增时间
    DELETED TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ETCD_SHIM_LEASE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主键
    ETCD_LEASE_ID INTEGER NOT NULL -- 租期 的 ID
    ETCD_TTL INTEGER NOT NULL -- 租期 的 时间长度，单位：秒
    ETCD_CREATED INTEGER,
    ETCD_DELETED INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 新增时间
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 最近更新时间
    PRIMARY KEY (ID)
);